---
title: "Jason Hou STA 363 Project 2"
author: "Jason Hou"
date: '2022-10-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
##Here we load the packages needed
library(ggplot2)
library(broom)
library(gridExtra)
library(dplyr)
library(class)
library(tidyverse)
library(gridExtra)
library(leaps)
library(corrplot)
library(RColorBrewer)
library(glmnet)
```
# Abstract

## Part 1 Introduction of Data

```{r load data}
vrboData<-read.csv("VRBO.csv")
```

```{r take a look}
glimpse(vrboData)
```


## Part 2: Data Cleaning

```{r checking and cleaning}
# Find out the number of missing values in the vrbo data set
sum(is.na(vrboData))
#Remove rows with missing values 
vrboCleaed<-na.omit(vrboData)
```

```{r correlation}
M<-cor(vrboCleaed[,-c(5,9,10)])
corrplot(M, method= "circle",type = "upper",title="Figure 2.1 Correlation Plot of Numeric Variables in Vrbo Data Set ")
#M
```

```{r}
vrboCleaed$neighborhood <-as.factor(vrboCleaed$neighborhood)
```

```{r}
table(vrboCleaed$neighborhood)
```















```{r}

```



```{r}

```


```{r}

```








```{r}

```


