---
title: "STA 363 Project 1"
author: "Jason Hou"
date: '2022-09-12'
output: html_document
---

#Abstract



#Section 1 Introduction and Data


```{r load packages}
library(ggplot2)
library(broom)
library(gridExtra)
library(dplyr)
library(class)
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}
dengue<-read.csv("dengueData.csv")
```

```{r checking}
sum(is.na(dengue))
na.omit(dengue)
```

```{r look}
glimpse(dengue)
```

#Section 2 KNN
## KNN Example

```{r data set for demo}
knnDemo<-data.frame("dengue_status"= dengue$Y,"Age"= dengue$Age, "Height"= dengue$Height)
```

```{r knn demo loop, eval=FALSE, include=FALSE}
n<-nrow(knnDemo)
set.seed(363663)
demoSelectRow<-sample(1:n,n*0.9,replace = "FALSE")
demoTrain<-knnDemo[demoSelectRow,]
demoTest<-knnDemo[-demoSelectRow,]

true1<-which(demoTest$dengue_status == 1)
true0<-which(demoTest$dengue_status == 0)

ntrue1<-length(true1)
ntrue0<-length(true0)

storeK<-data.frame("K"=rep(NA,50),"GMean"=rep(NA,50))

for(i in 1:50){
  storeK$K[i]<-i
  Kpreds<-knn(demoTrain[,c(2,3)],demoTest[,c(2,3)],k=i,cl=demoTrain$dengue_status)
  sensitivity<-sum(Kpreds[true1] == 1)/ntrue1
  specificity<-sum(Kpreds[true0] == 0)/ntrue0
  storeK$GMean[i]<-sqrt(sensitivity*specificity)
}

knnDemoPlot<-ggplot(storeK,aes(K,GMean))+
  geom_line()+
  labs(caption = paste("Geometric Mean, ReD Line at K=", which.max(storeK$GMean)),title = "Figure 1",y = " ")+
  geom_vline(xintercept = which.max(storeK$GMean),lty = 2,col="red")
knnDemoPlot
#
```





```{r create example sets}
numb<-nrow(knnDemo)
DemoSubsetRow<-sample(1:numb,numb*0.01,replace = FALSE)
SetForDemo<-knnDemo[DemoSubsetRow,]  

demoNum<-nrow(SetForDemo)
SelectIn_Demo<-sample(1:demoNum,demoNum*0.7,replace = FALSE)
demoTrain<-SetForDemo[SelectIn_Demo,]
demoTest<-SetForDemo[-SelectIn_Demo,]
```


```{r knn true demo}
demoTrain<-demoTrain%>%
  mutate(dengue_status=as.character(dengue_status))
demoTest<-demoTest%>%
  mutate(dengue_status_test=as.character(dengue_status))
ggplot()+
  geom_point(data = demoTrain,aes(x=Age,y=Height,col=dengue_status),size=2,alpha=0.9,shape=19)+
  geom_point(data =demoTest,aes(x=Age,y=Height),size=2,alpha=0.9,shape=4)
  
  
```

```{r knn prediction example}
example_data<-data.frame("Age"= rep(NA,1),"Height"=rep(NA,1))
example_data$Age[1]<-8
example_data$Height[1]<-100


#Kpreds_sample<-knn(demoTrain[,c(2,3)],example_data[,c(1,2)],k=i,cl=demoTrain$dengue_status)

for(j in 1:20){
  Kpreds_sample<-knn(demoTrain[,c(2,3)],example_data[,c(1,2)],k=j,cl=demoTrain$dengue_status)
  
}
```



```{r creating actual KNN set and mutate logical var, eval=FALSE, include=FALSE}
knnActual<-dengue
knnActual<-knnActual%>%
  mutate(Flush=as.character(Flush),
        Hepatomegaly=as.character(Hepatomegaly),
        Rash=as.character(Rash))
knnActual<-knnActual%>%
  mutate(Flush = recode(Flush,"TRUE" = "1",
         "FALSE" = "0"),
         Hepatomegaly = recode(Hepatomegaly,"TRUE" = "1",
                               "FALSE" = "0"),
         Rash = recode(Rash,"TRUE" = "1",
                      "FALSE" = "0"))
```


### Manually split data

```{r 20-80 split}
q<-nrow(dengue)
set.seed(363663)
manually_select<-sample(1:q,q*0.8,replace = "FALSE")
manual_train<-dengue[manually_select,]
manual_test<-dengue[-manually_select,]
storage_split<-data.frame("K"= rep(NA,50),"Sensitivity" = rep(NA,50),"Specificity" = rep(NA,50),"GeoMean"= rep(NA,50))

for(t in 1:50){
  storage_split$K[t]<-t
  k_preds_split<-knn(manual_train[,c(2,3,8,9)],manual_test[,c(2,3,8,9)],k=t,cl=manual_train$Y)
  
  
  #Find rows with positive and negative result
    true1_split<-which(manual_test$Y == 1)
    true0_split<-which(manual_test$Y == 0)
    
    #Compute the amount of rows corresponding to each result
    ntrue1_split<-length(true1_split)
    ntrue0_split<-length(true0_split)
  
  sensitivity_split<-sum(k_preds_split[true1_split] == 1)/ntrue1_split
  storage_split$Sensitivity[t]<-sensitivity
  specificity_split<-sum(k_preds[ntrue0_split] == 0)/ntrue0_split
  storage_split$specificity_split[t]<-specificity
  storage_split$GeoMean[t]<-sqrt(sensitivity*specificity)
}

```


```{r 80-20 plot}
#Create plot to find the best k for KNN 
knnSplit<-ggplot(storage_split,aes(K,GeoMean))+
  geom_line()+
  labs(caption = paste("Geometric Mean, ReD Line at K=", which.max(storage_split$GeoMean)),title = "Figure 1",y = " ")+
  geom_vline(xintercept = which.max(storage_split$GeoMean),lty = 2,col="red")
knnSplit
```



```{r k fold determine best k}
n<-nrow(knnActual)
nk<-50
storage<-data.frame("K"=rep(NA,nk),
                    "Sensitivity" = rep(NA,nk),
                    "Specificity" = rep(NA,nk),
                    "GeoMean" = rep(NA,nk))

#Creating pools and set fold for K fold CV
set.seed(363663)
pool<-rep(1:10,573)

fold<-sample(pool,5726,replace = FALSE)

#Outer loop for incrementing k 
for(k in 1:nk){
  storage$K[k]<-k
  
  storage_inner<-data.frame("YHat" = rep(NA,n))
  #Inner loop for 10 fold cv
  for(i in 1:10){
    #Find data in each fold
    infold<-which(fold == i)
    
    #Create training and testing sets
    Train_Dengue<-knnActual[-infold,]
    Test_Dengue<-knnActual[infold,]
    
    #Run Knn
    k_preds<-knn(Train_Dengue[,c(2,3,8,9)],Test_Dengue[,c(2,3,8,9)],k=k,cl=Train_Dengue$Y)
    
    #store results
    storage_inner$YHat[infold]<-as.numeric(as.character(k_preds))
    
    #Find rows with positive and negative result
    true1<-which(Test_Dengue$Y == 1)
    true0<-which(Test_Dengue$Y == 0)
    
    #Compute the amount of rows corresponding to each result
    ntrue1<-length(true1)
    ntrue0<-length(true0)
    #Compute sensitivity and specificity, as well as GeoMean for determining the best value for k

    sensitivity<-sum(k_preds[true1] == 1)/ntrue1
    storage$Sensitivity[k]<-sensitivity
    specificity<-sum(k_preds[true0] == 0)/ntrue0
    storage$Specificity[k]<-specificity
    storage$GeoMean[k]<-sqrt(sensitivity*specificity)
    
  }
  
}

```

```{r find best k}
#Create plot to find the best k for KNN 
knnActualPlot<-ggplot(storage,aes(K,GeoMean))+
  geom_line()+
  labs(caption = paste("Geometric Mean, ReD Line at K=", which.max(storage$GeoMean)),title = "Figure 1",y = " ")+
  geom_vline(xintercept = which.max(storage$GeoMean),lty = 2,col="red")
knnActualPlot
```

```{r}
knitr::kable(table(storage_inner$YHat, dengue$Y), caption= "Table 1: Confusion Matrix ", col = c("True Not", "True Dengue"))
```

```{r using best k to do a knn again k = 35}
#create storage for prediction result
storage_inner_trial<-data.frame("pred"=rep(NA,5726))
#run 10 fold knn with best k value = 35
 for(i in 1:10){
   
   #Find data in each fold
    infold<-which(fold == i)
    
    #Creating Training and testing set
    Train_Dengue<-knnActual[-infold,]
    Test_Dengue<-knnActual[infold,]
    #Run knn
    k_preds_best<-knn(Train_Dengue[,c(2,3,8,9)],Test_Dengue[,c(2,3,8,9)],k=35,cl=Train_Dengue$Y)
    #store result
    storage_inner_trial$pred[infold]<-as.numeric(as.character(k_preds))
    
    
 }
#Compute sensitivity and specificity,formating them
sensitivity2<-sum(k_preds[true1] == 1)/ntrue1
knitr::kable(sensitivity)
specificity2<-sum(k_preds[true0] == 0)/ntrue0
knitr::kable(table(storage_inner_trial$pred, dengue$Y), caption= "Table 1: Confusion Matrix ", col = c("True Not", "True Dengue"))  
```
Age, Daydisease, temperature and BMI are the only four included in the prediction. Body height and weight was dropped from prediction since they are highly correlated with BMI(according to BMI formula)and  would create multicolinearity in the prediction.
         


